package formularios;

import complementos.AlgoritimoMergeSort;
import complementos.AlgoritimoQuicksort;
import complementos.AlgoritimoSort;
import complementos.Lertxt;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



public class FormMenu extends javax.swing.JFrame {
    Lertxt ler = new Lertxt();    
    long init;
    long end;  
    long total;
    
    public FormMenu() throws IOException {        
        initComponents();
        jTALer.setEditable(false);
        jTASort.setEditable(false);
        jLabel1.setIcon(new javax.swing.ImageIcon("java-img.gif"));        
        jLabel1.setVisible(false);   
        IniciaTxtLer();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTALer = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTINVERSOES = new javax.swing.JTextField();
        jTTEMPO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTASort = new javax.swing.JTextArea();
        jPLoading = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sort - Elder Xavier");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setText("Sort");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Merge Sort");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Quick Sort");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton2)
                .addGap(42, 42, 42)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTALer.setColumns(20);
        jTALer.setRows(5);
        jScrollPane1.setViewportView(jTALer);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setToolTipText("Sort");

        jLabel2.setText("Inverssões:");

        jLabel3.setText("Tempo (ms):");

        jPanel4.setBackground(java.awt.Color.white);

        jTASort.setColumns(20);
        jTASort.setRows(5);
        jScrollPane2.setViewportView(jTASort);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTINVERSOES, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTTEMPO, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTINVERSOES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTTEMPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Carregando...");

        javax.swing.GroupLayout jPLoadingLayout = new javax.swing.GroupLayout(jPLoading);
        jPLoading.setLayout(jPLoadingLayout);
        jPLoadingLayout.setHorizontalGroup(
            jPLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoadingLayout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPLoadingLayout.setVerticalGroup(
            jPLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLoadingLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32))
        );

        jMenu1.setText("Arquivo");

        jMenuItem3.setText("Novo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        jMenuItem2.setText("Sobre o Sort");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false); 
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTASort.setText("");
        jTINVERSOES.setText("");
        jTTEMPO.setText("");
        Sort();            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jTINVERSOES.setText("");
        jTTEMPO.setText("");
        jTALer.setText("");        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTASort.setText("");
        jTINVERSOES.setText("");
        jTTEMPO.setText("");
        MergeSort();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            jTASort.setText("");
            jTINVERSOES.setText("");
            jTTEMPO.setText("");
            QuickSort();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        java.awt.EventQueue.invokeLater(() -> {
            
            try {                
                new FormMenu().setVisible(true);          
            } catch (IOException ex) {
                Logger.getLogger(FormMenu.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex, "Error:", JOptionPane.ERROR_MESSAGE);
            }
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPLoading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTALer;
    private javax.swing.JTextArea jTASort;
    private javax.swing.JTextField jTINVERSOES;
    private javax.swing.JTextField jTTEMPO;
    // End of variables declaration//GEN-END:variables

    private void IniciaTxtLer() {  
        jLabel1.setVisible(true); 
        jTASort.setVisible(false); 
        Thread threadinicia = new Thread() {
            @Override
            public void run(){
                try{
                    DisableButtons();
                    int array[] = ler.converteInt("vetoInteiros.txt");
                    for( int i =0 ; i < array.length; i++){
                        jTALer.append(String.valueOf(array[i])+ "\n");
                    }                    
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, ex, "Error:", JOptionPane.ERROR_MESSAGE);
                }
            }

        };
        
        Thread load = new Thread() {  
            public @Override void run() {                  
                if (threadinicia.getState() == Thread.State.NEW) 
                    threadinicia.start(); 
                if (threadinicia.getState() != Thread.State.TERMINATED)
                    try {  
                        threadinicia.join(); 
                    } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex, "Error:", JOptionPane.ERROR_MESSAGE);
                    }                  
                jLabel1.setVisible(false);
                EnableButtons();                
            }  
        };          
        threadinicia.start();
        load.start();
        
    }
    
    
    public void QuickSort() {
        jLabel1.setVisible(true);
        
                
        Thread threadinicia = new Thread() {
            @Override
            public void run(){
                try{
                    DisableButtons();
                    jTASort.setVisible(false); 
                    init = System.currentTimeMillis();  
                    AlgoritimoQuicksort sorter = new AlgoritimoQuicksort(); 
                    int array[] = ler.converteInt("src/arquivos/vetoInteiros.txt");
                    sorter.sort(array);        
                    for(int i:array){        
                        jTASort.append(String.valueOf(i)+ "\n");
                    }                        
                
                jTINVERSOES.setText(String.valueOf(sorter.getInterations()));
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, ex, "Error:", JOptionPane.ERROR_MESSAGE);
                }
            }
        };
        
        Thread load = new Thread() {  
            public @Override void run() {                  
                if (threadinicia.getState() == Thread.State.NEW) 
                    threadinicia.start(); 
                if (threadinicia.getState() != Thread.State.TERMINATED)
                    try {  
                        threadinicia.join(); 
                    } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex, "Error:", JOptionPane.ERROR_MESSAGE);
                    }  
                end = System.currentTimeMillis();
                total = end - init;  
                jTTEMPO.setText(""+(total));
                jLabel1.setVisible(false); 
                jTASort.setVisible(true); 
                EnableButtons();                
            }  
        };          
        threadinicia.start();
        load.start();
        
    }
    
    public void MergeSort() {
        jLabel1.setVisible(true);
         
                
        Thread threadinicia = new Thread() {
            @Override
            public void run(){
                try{      
                    DisableButtons();
                    jTASort.setVisible(false);
                    init = System.currentTimeMillis();                  
                    AlgoritimoMergeSort sorter = new AlgoritimoMergeSort();                
                    int array[] = ler.converteInt("src/arquivos/vetoInteiros.txt");
                    int array2[] = sorter.sort(array);
                    sorter.sort(array2);        
                    for(int i:array2){        
                        jTASort.append(String.valueOf(i)+ "\n");
                    }                                        
                jTINVERSOES.setText(""+sorter.getIntetions());                                
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, ex, "Error:", JOptionPane.ERROR_MESSAGE);
                }
            }
        };
        
        Thread load = new Thread() {  
            public @Override void run() {                  
                if (threadinicia.getState() == Thread.State.NEW) 
                    threadinicia.start(); 
                if (threadinicia.getState() != Thread.State.TERMINATED)
                    try {  
                        threadinicia.join(); 
                    } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex, "Error:", JOptionPane.ERROR_MESSAGE);
                    }  
                end = System.currentTimeMillis();
                total = end - init;  
                jTTEMPO.setText(""+(total));
                jLabel1.setVisible(false); 
                jTASort.setVisible(true); 
                EnableButtons();
            }  
        };          
        threadinicia.start();
        load.start();
        
    }
    
    public void Sort() {
        jLabel1.setVisible(true);
        
                
        Thread threadinicia = new Thread() {
            @Override
            public void run(){
                try{  
                    DisableButtons();
                    jTASort.setVisible(false);                
                    init = System.currentTimeMillis();                  
                    AlgoritimoSort sorter = new AlgoritimoSort();
                    int array[] = ler.converteInt("src/arquivos/vetoInteiros.txt");
                    sorter.sort(array);        
                    for(int i:array){        
                        jTASort.append(String.valueOf(i)+ "\n");
                    }                        

                    jTINVERSOES.setText(""+sorter.getInterations());                                
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, ex, "Error:", JOptionPane.ERROR_MESSAGE);
                }
            }
        };
        
        Thread load = new Thread() {  
            public @Override void run() {                  
                if (threadinicia.getState() == Thread.State.NEW) 
                    threadinicia.start(); 
                if (threadinicia.getState() != Thread.State.TERMINATED)
                    try {  
                        threadinicia.join(); 
                    } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex, "Error:", JOptionPane.ERROR_MESSAGE);
                    }  
                end = System.currentTimeMillis();
                total = end - init;  
                jTTEMPO.setText(""+(total));
                jLabel1.setVisible(false);
                jTASort.setVisible(true);
                EnableButtons();
                
            }  
        };          
        threadinicia.start();
        load.start();
        
    }
    
    private void EnableButtons(){
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
    }
    private void DisableButtons(){
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }

}

